services:
  vovan-worker:
    build: .
    container_name: vovan-worker
    env_file:
      - .env
    command: ["worker"]
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
